language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - rbx-19mode
env:
  - BIORUBY_RAKE_DEFAULT_TASK=test
  - BIORUBY_RAKE_DEFAULT_TASK=gem-integration-test
  - BIORUBY_RAKE_DEFAULT_TASK=tar-integration-test
gemfile:
  - gemfiles/Gemfile.travis-ruby1.9
  - gemfiles/Gemfile.travis-ruby1.8
  - gemfiles/Gemfile.travis-jruby1.9
  - gemfiles/Gemfile.travis-jruby1.8
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.travis-ruby1.9
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.travis-jruby1.8
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.travis-jruby1.9
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.travis-ruby1.8
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.travis-jruby1.8
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.travis-jruby1.9
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-ruby1.8
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-ruby1.9
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.8
    - rvm: rbx-19mode
      gemfile: gemfiles/Gemfile.travis-ruby1.8
    - rvm: rbx-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.8
    - rvm: rbx-19mode
      gemfile: gemfiles/Gemfile.travis-jruby1.9

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

#before_install:
# - sudo apt-get update
# - sudo apt-get install libxml2-dev libexpat1-dev
after_install:
 - rake regemspec

# whitelist branches
branches:
  only:
    - master

